version: 0.0
os: linux

files:
  - source: student.war
    destination: /opt/apache-tomcat-8.5.82/webapps/
    
file_exists_behavior: OVERWRITE    
          
hooks:
  BeforeInstall:
    - location: scripts/pre-installation.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_service.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: root 
